//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class acr_trnd
    {
        public string site { get; set; }
        public string kind { get; set; }
        public string acr_nbr { get; set; }
        public string acr_seq { get; set; }
        public string order_seq { get; set; }
        public string transaction_class { get; set; }
        public string adjust_code { get; set; }
        public string reference_no { get; set; }
        public Nullable<decimal> detail_amt { get; set; }
        public string detail_remark { get; set; }
        public string reason { get; set; }
        public string rs_type { get; set; }
        public string item_no { get; set; }
        public string stockroom { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> acr_qty { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public string note_nbr { get; set; }
        public string note_type { get; set; }
        public string note_owner { get; set; }
        public string note_city { get; set; }
        public string note_issuer { get; set; }
        public string iss_main_bank { get; set; }
        public string iss_branch_bank { get; set; }
        public string iss_bank_account { get; set; }
        public string cash_main_bank { get; set; }
        public string cash_branch_bank { get; set; }
        public string cash_bank_account { get; set; }
        public Nullable<System.DateTime> note_rec_date { get; set; }
        public Nullable<System.DateTime> note_due_date { get; set; }
        public Nullable<decimal> change_offset_method { get; set; }
        public string change_reference_no { get; set; }
        public string select_balance_type { get; set; }
        public string source_kind { get; set; }
        public string source_nbr { get; set; }
        public string source_seq { get; set; }
        public string project_id { get; set; }
        public string acr_detail_status { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string invoice_nbr { get; set; }
        public string adv_tax_code { get; set; }
        public Nullable<decimal> rate_amt { get; set; }
        public Nullable<decimal> base_detail_amt { get; set; }
        public Nullable<decimal> base_untax_amt { get; set; }
        public string cus_id { get; set; }
        public string offset_currency { get; set; }
        public Nullable<decimal> offset_exchange { get; set; }
        public string team_dept { get; set; }
        public Nullable<decimal> detail_tax { get; set; }
        public Nullable<decimal> base_detail_tax { get; set; }
        public Nullable<decimal> detail_untax { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string ord_nbr { get; set; }
        public string ord_seq { get; set; }
        public string cust_po_nbr { get; set; }
        public string prod_nbr { get; set; }
        public string ord_class { get; set; }
        public string item_statistic { get; set; }
        public string style_no { get; set; }
        public Nullable<decimal> accu_exchange { get; set; }
    }
}
