//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class acr_trnm
    {
        public string site { get; set; }
        public string kind { get; set; }
        public string acr_nbr { get; set; }
        public Nullable<System.DateTime> acr_date { get; set; }
        public string transaction_code { get; set; }
        public string cus_id { get; set; }
        public string adv_reference_no { get; set; }
        public string post_reference_no { get; set; }
        public Nullable<decimal> post_adv_amt { get; set; }
        public string employee_no { get; set; }
        public string dept_no { get; set; }
        public string area_no { get; set; }
        public string pay_term { get; set; }
        public string currency_id { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public string offset_currency { get; set; }
        public Nullable<decimal> offset_exchange { get; set; }
        public string carrier_id { get; set; }
        public string transatn_term { get; set; }
        public string order_nbr { get; set; }
        public string invoice_nbr { get; set; }
        public Nullable<decimal> local_invoice_no { get; set; }
        public string tax_code { get; set; }
        public Nullable<decimal> tax_amt { get; set; }
        public Nullable<decimal> sale_total_amt { get; set; }
        public string cash_flag { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<decimal> discount_amt { get; set; }
        public Nullable<decimal> acr_amt { get; set; }
        public Nullable<decimal> note_amt { get; set; }
        public Nullable<decimal> bank_amt { get; set; }
        public Nullable<decimal> cash_amt { get; set; }
        public Nullable<decimal> return_amt { get; set; }
        public Nullable<decimal> other1_amt { get; set; }
        public Nullable<decimal> other2_amt { get; set; }
        public Nullable<decimal> acr_adv_amt { get; set; }
        public Nullable<decimal> reject_amt { get; set; }
        public Nullable<System.DateTime> acr_due_date { get; set; }
        public string affect_column { get; set; }
        public Nullable<decimal> offset_method { get; set; }
        public string data_source { get; set; }
        public string acr_head_status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string proc_mask { get; set; }
        public string stax_reason { get; set; }
        public string adv_reason { get; set; }
        public string ptax_reason { get; set; }
        public Nullable<decimal> base_tax_amt { get; set; }
        public Nullable<decimal> base_tot_amt { get; set; }
        public Nullable<System.DateTime> account_date { get; set; }
        public string team_dept { get; set; }
        public string keyin_user { get; set; }
        public string issuer { get; set; }
        public Nullable<System.DateTime> invoice_date { get; set; }
        public string invoice_flag { get; set; }
        public Nullable<decimal> acp_amt { get; set; }
    }
}
