//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class acr_trn_check
    {
        public int uid { get; set; }
        public string create_timestamp { get; set; }
        public string CheckFlag { get; set; }
        public System.DateTime CheckCreateDate { get; set; }
        public Nullable<System.DateTime> CheckModifyDate { get; set; }
        public string ticket { get; set; }
        public Nullable<int> AcrTaxID { get; set; }
        public string site { get; set; }
        public string kind { get; set; }
        public string acr_nbr { get; set; }
        public Nullable<System.DateTime> acr_date { get; set; }
        public string transaction_code { get; set; }
        public string transaction_class { get; set; }
        public string reverse_code { get; set; }
        public Nullable<decimal> offset_method { get; set; }
        public string cus_id { get; set; }
        public string invoice_nbr { get; set; }
        public string employee_no { get; set; }
        public string dept_no { get; set; }
        public string area_no { get; set; }
        public string pay_term { get; set; }
        public string carrier_id { get; set; }
        public string transatn_term { get; set; }
        public string currency_id { get; set; }
        public Nullable<decimal> exchange_rate { get; set; }
        public Nullable<decimal> offset_exchange { get; set; }
        public string offset_currency { get; set; }
        public Nullable<decimal> local_invoice_no { get; set; }
        public string tax_code { get; set; }
        public Nullable<decimal> tax_amt { get; set; }
        public string affect_column { get; set; }
        public Nullable<decimal> discount_rate { get; set; }
        public Nullable<decimal> discount_amt { get; set; }
        public string cash_flag { get; set; }
        public string data_source { get; set; }
        public string acr_seq { get; set; }
        public string order_nbr { get; set; }
        public string order_seq { get; set; }
        public string adjust_code { get; set; }
        public string reference_no { get; set; }
        public Nullable<decimal> foreign_amt { get; set; }
        public Nullable<decimal> base_amt { get; set; }
        public string remark40 { get; set; }
        public string reason { get; set; }
        public string rs_type { get; set; }
        public string item_no { get; set; }
        public string stockroom { get; set; }
        public string unit { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> acr_qty { get; set; }
        public Nullable<decimal> detail_amt { get; set; }
        public string iss_main_bank { get; set; }
        public string iss_branch_bank { get; set; }
        public string iss_bank_account { get; set; }
        public string cash_main_bank { get; set; }
        public string cash_branch_bank { get; set; }
        public string cash_bank_account { get; set; }
        public string note_nbr { get; set; }
        public string note_type { get; set; }
        public string note_owner { get; set; }
        public string note_city { get; set; }
        public string note_issuer { get; set; }
        public Nullable<System.DateTime> acr_counter_date { get; set; }
        public Nullable<System.DateTime> acr_due_date { get; set; }
        public Nullable<System.DateTime> note_due_date { get; set; }
        public Nullable<System.DateTime> note_rec_date { get; set; }
        public string posted_bal { get; set; }
        public string posted_nms { get; set; }
        public string posted_ais { get; set; }
        public string acr_status { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string project_id { get; set; }
        public string adv_tax_code { get; set; }
        public Nullable<System.DateTime> account_date { get; set; }
        public string team_dept { get; set; }
        public string keyin_user { get; set; }
        public string issuer { get; set; }
        public string ord_nbr { get; set; }
        public string ord_seq { get; set; }
        public string cust_po_nbr { get; set; }
        public string prod_nbr { get; set; }
        public string ord_class { get; set; }
        public string item_statistic { get; set; }
        public string style_no { get; set; }
    }
}
