//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class bas_employee
    {
        public string site { get; set; }
        public string employee_no { get; set; }
        public string employee_name { get; set; }
        public string employee_status { get; set; }
        public string email_address { get; set; }
        public string dept_no { get; set; }
        public string tel_nbr { get; set; }
        public string sec_dept { get; set; }
        public string mobile_phone { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string employee_name_eng { get; set; }
    }
}
