//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGFRequestMark
    {
        public int id { get; set; }
        public int uid { get; set; }
        public string 修改人員 { get; set; }
        public string 工號 { get; set; }
        public string 處理類別 { get; set; }
        public string 處理時間 { get; set; }
        public string 原因碼 { get; set; }
        public string 原因 { get; set; }
        public System.DateTime 建立日期 { get; set; }
        public string Creator { get; set; }
        public int 狀態 { get; set; }
        public Nullable<System.DateTime> 修改日期 { get; set; }
        public string Modifier { get; set; }
        public int 件數 { get; set; }
        public string 備註 { get; set; }
    }
}
