//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGFRequestSam
    {
        public int uid { get; set; }
        public string site { get; set; }
        public string sam_nbr { get; set; }
        public string SampleType { get; set; }
        public string SampleUser { get; set; }
        public string SampleNo { get; set; }
        public decimal Qty { get; set; }
        public string Remark { get; set; }
        public string SampleCreatDate { get; set; }
        public string 原因碼 { get; set; }
        public string 原因 { get; set; }
        public System.DateTime CreatDate { get; set; }
        public string Creator { get; set; }
        public int Flag { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string Modifier { get; set; }
        public string 馬克 { get; set; }
        public string 修改馬克 { get; set; }
        public string 馬克完成日 { get; set; }
    }
}
