//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestGroupEntities : DbContext
    {
        public TestGroupEntities()
            : base("name=TestGroupEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<acr_trn> acr_trn { get; set; }
        public virtual DbSet<acr_trn_check> acr_trn_check { get; set; }
        public virtual DbSet<acr_trnd> acr_trnd { get; set; }
        public virtual DbSet<acr_trnm> acr_trnm { get; set; }
        public virtual DbSet<purc_pkd> purc_pkd { get; set; }
        public virtual DbSet<purc_pkd_for_acr> purc_pkd_for_acr { get; set; }
        public virtual DbSet<purc_pkm> purc_pkm { get; set; }
        public virtual DbSet<purc_pkm_for_acr> purc_pkm_for_acr { get; set; }
    }
}
