//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGF多語對照表
    {
        public int id { get; set; }
        public string 程式 { get; set; }
        public string 資料代號 { get; set; }
        public string 中文 { get; set; }
        public string 英文 { get; set; }
        public string 越文 { get; set; }
        public string 說明 { get; set; }
        public System.DateTime 建立時間 { get; set; }
        public Nullable<System.DateTime> 異動時間 { get; set; }
    }
}
