//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class purc_pkm_for_acr
    {
        public string site { get; set; }
        public string pak_nbr { get; set; }
        public Nullable<System.DateTime> pak_date { get; set; }
        public string CheckFlag { get; set; }
        public System.DateTime CheckCreateDate { get; set; }
        public Nullable<int> acr_uid { get; set; }
        public string sono { get; set; }
        public string carrier_id { get; set; }
        public string pick_port { get; set; }
        public string port_of_destination { get; set; }
        public string owner { get; set; }
        public string sender { get; set; }
        public string addressee { get; set; }
        public string vessel { get; set; }
        public string voyage { get; set; }
        public string cabinet_no { get; set; }
        public string cabinet_type { get; set; }
        public Nullable<System.DateTime> dta_date { get; set; }
        public Nullable<System.DateTime> etd_date { get; set; }
        public Nullable<System.DateTime> etc_date { get; set; }
        public Nullable<System.DateTime> arrival_date { get; set; }
        public string pkm_status { get; set; }
        public Nullable<decimal> tot_box_qty { get; set; }
        public Nullable<decimal> tot_net_wt { get; set; }
        public Nullable<decimal> tot_gross_wt { get; set; }
        public Nullable<decimal> tot_cube_feet { get; set; }
        public string filter_creator { get; set; }
        public string filter_dept { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string so_nbr { get; set; }
        public string decl_no { get; set; }
        public string bol_no { get; set; }
        public Nullable<decimal> ship_cost { get; set; }
        public Nullable<decimal> ins_amt { get; set; }
        public string pur_kind { get; set; }
        public string vendor_id { get; set; }
    }
}
