//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class purc_pkd_for_acr
    {
        public int uid { get; set; }
        public string site { get; set; }
        public string pak_nbr { get; set; }
        public string pak_seq { get; set; }
        public string acr_ticket { get; set; }
        public string CheckFlag { get; set; }
        public System.DateTime CheckCreateDate { get; set; }
        public Nullable<int> AcrTaxID { get; set; }
        public string cus_item_no { get; set; }
        public string rec_nbr { get; set; }
        public string rec_seq { get; set; }
        public string stockroom { get; set; }
        public string rs_type { get; set; }
        public Nullable<decimal> uncount_qty { get; set; }
        public Nullable<decimal> coint_qty { get; set; }
        public string item_no { get; set; }
        public string box_no { get; set; }
        public Nullable<decimal> box_qty { get; set; }
        public Nullable<decimal> tot_net_wt { get; set; }
        public Nullable<decimal> tot_gross_wt { get; set; }
        public Nullable<decimal> cube_feet { get; set; }
        public string rec_unit { get; set; }
        public Nullable<decimal> pur_price { get; set; }
        public Nullable<decimal> rec_qty { get; set; }
        public Nullable<decimal> customs_decleartion_price { get; set; }
        public Nullable<decimal> customs_decleartion_amt { get; set; }
        public Nullable<decimal> clear_Customs_price { get; set; }
        public string currency_id { get; set; }
        public string combine { get; set; }
        public string pkd_status { get; set; }
        public string filter_creator { get; set; }
        public string filter_dept { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string vendor_id { get; set; }
        public Nullable<decimal> PreAmt { get; set; }
    }
}
