//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class samc_reqm
    {
        public string site { get; set; }
        public string sam_nbr { get; set; }
        public string sam_times { get; set; }
        public string sam_no { get; set; }
        public string version { get; set; }
        public Nullable<System.DateTime> sam_date { get; set; }
        public string cus_id { get; set; }
        public string dept_no { get; set; }
        public string item_no { get; set; }
        public string type_id { get; set; }
        public string salesman { get; set; }
        public string sam_size { get; set; }
        public Nullable<decimal> assign_qty { get; set; }
        public Nullable<System.DateTime> plan_fin_date { get; set; }
        public string emb { get; set; }
        public string washing { get; set; }
        public string oth_extra { get; set; }
        public Nullable<System.DateTime> finish_date { get; set; }
        public Nullable<decimal> finish_qty { get; set; }
        public string place_origin { get; set; }
        public string currency_id { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<decimal> sam_qty { get; set; }
        public Nullable<decimal> sam_cus_qty { get; set; }
        public Nullable<decimal> sam_taipei_qty { get; set; }
        public string image_path { get; set; }
        public string remark60 { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> close_date { get; set; }
        public string reason { get; set; }
        public Nullable<System.DateTime> online_date { get; set; }
        public string confirm_yn { get; set; }
        public string progress_rate { get; set; }
        public string sam_class { get; set; }
        public string original_sampleo_yn { get; set; }
        public string original_edition_yn { get; set; }
        public string original_edition_size { get; set; }
        public string ratio_size { get; set; }
        public string sample_complete_1 { get; set; }
        public string sample_complete_2 { get; set; }
        public string cus_express_corp { get; set; }
        public string cus_assign_account { get; set; }
        public string cus_address_id { get; set; }
        public string cus_addressee { get; set; }
        public string cus_address { get; set; }
        public string cus_style_no { get; set; }
        public string brand_name { get; set; }
        public string sam_type { get; set; }
        public string proofing_factory { get; set; }
        public string filter_creator { get; set; }
        public string filter_dept { get; set; }
        public string creator { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modifier { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public string printing { get; set; }
        public string sewing { get; set; }
        public string samc_remark60 { get; set; }
        public string mark { get; set; }
        public string crp_yn { get; set; }
        public Nullable<System.DateTime> crp_date { get; set; }
        public string item_statistic { get; set; }
        public string remark_1 { get; set; }
        public string final { get; set; }
        public Nullable<System.DateTime> last_date { get; set; }
        public Nullable<System.DateTime> samc_fin_date { get; set; }
        public string sam_type_A { get; set; }
        public string sam_type_B { get; set; }
        public string sam_type_C { get; set; }
        public string sam_type_D { get; set; }
        public string sam_type_E { get; set; }
        public string sam_type_F { get; set; }
        public string hotfix { get; set; }
        public Nullable<System.DateTime> s_plan_arrival_date { get; set; }
        public Nullable<System.DateTime> s_real_arrival_date { get; set; }
        public string sam_type_G { get; set; }
        public Nullable<System.DateTime> samc_plan_fin_date { get; set; }
        public string original_edition { get; set; }
        public string reason_remark { get; set; }
        public Nullable<System.DateTime> sale_finish_date { get; set; }
        public string receipt_yn { get; set; }
        public Nullable<System.DateTime> receipt_date { get; set; }
        public string samc_factory { get; set; }
        public string sam_type_H { get; set; }
        public string season_y { get; set; }
        public string season { get; set; }
        public Nullable<System.DateTime> big_date { get; set; }
        public Nullable<System.DateTime> td_fin_date { get; set; }
        public Nullable<System.DateTime> sam_in_date { get; set; }
        public Nullable<System.DateTime> sam_out_date { get; set; }
        public Nullable<System.DateTime> td_in_date { get; set; }
    }
}
