//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGFPortal.DataSetSource
{
    using System;
    using System.Collections.Generic;
    
    public partial class View廠商付款條件
    {
        public string 公司別 { get; set; }
        public string 廠商代號 { get; set; }
        public string 廠商名稱 { get; set; }
        public string 廠商簡稱 { get; set; }
        public string 統一編號 { get; set; }
        public string 地址 { get; set; }
        public string 地址2 { get; set; }
        public string dept_no { get; set; }
        public string buyer { get; set; }
        public string 負責人 { get; set; }
        public string boss_tel { get; set; }
        public string carrier_id { get; set; }
        public string 國家 { get; set; }
        public string 英文名稱 { get; set; }
        public string remark60_1 { get; set; }
        public string remark60_2 { get; set; }
        public string 付款代號 { get; set; }
        public string 付款名稱 { get; set; }
        public string 交易代號 { get; set; }
        public string 交易名稱 { get; set; }
    }
}
